# Generated by Django 2.1 on 2019-12-05 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceUuid', models.CharField(max_length=50)),
                ('deviceName', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=15)),
                ('ipAddr', models.CharField(default='ip', max_length=250)),
                ('macAddr', models.CharField(default='mac', max_length=250)),
                ('os', models.CharField(max_length=35)),
                ('processor', models.CharField(max_length=80)),
                ('cpu', models.CharField(max_length=10)),
                ('memoryCapacity', models.CharField(max_length=10)),
                ('registry_StartupCommand', models.TextField(blank=True)),
                ('latest_scan_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents')),
                ('uploaded_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField(blank=True)),
                ('file_hash_sha1', models.CharField(max_length=40)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('file_state', models.IntegerField(blank=True, null=True)),
                ('peutils_packed', models.CharField(blank=True, max_length=200)),
                ('entropy', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('create_time', models.CharField(blank=True, max_length=30, null=True)),
                ('modified_time', models.CharField(blank=True, max_length=30, null=True)),
                ('accessed_time', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('product', models.CharField(blank=True, max_length=50, null=True)),
                ('prod_version', models.CharField(blank=True, max_length=40, null=True)),
                ('file_version', models.CharField(blank=True, max_length=40, null=True)),
                ('machine_type', models.CharField(blank=True, max_length=20, null=True)),
                ('signature_verification', models.CharField(max_length=100, null=True)),
                ('link_date', models.CharField(blank=True, max_length=30, null=True)),
                ('signing_date', models.CharField(blank=True, max_length=30, null=True)),
                ('signer', models.TextField(blank=True, default=[])),
                ('counter_signer', models.TextField(blank=True, default=[])),
                ('pe_machine', models.IntegerField(blank=True, null=True)),
                ('pe_sectionNum', models.IntegerField(blank=True, null=True)),
                ('pe_timeDateStamp', models.IntegerField(blank=True, null=True)),
                ('pe_characteristics', models.IntegerField(blank=True, null=True)),
                ('pe_entryPoint', models.IntegerField(blank=True, null=True)),
                ('pe_sections', models.TextField(blank=True, default=[])),
                ('pe_imports', models.TextField(blank=True, default={})),
                ('pe_exports', models.TextField(blank=True, default=[])),
                ('network_ability', models.BooleanField()),
                ('rw_ability', models.BooleanField()),
                ('exec_ability', models.BooleanField()),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='RSAKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScanningRecord',
            fields=[
                ('scan_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(max_length=30)),
                ('end_time', models.CharField(max_length=30)),
                ('normal_option', models.BooleanField()),
                ('advance_option', models.BooleanField()),
                ('customized_option', models.BooleanField()),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Computer')),
            ],
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='scanningRecord_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ScanningRecord'),
        ),
    ]
