# Generated by Django 2.1 on 2019-11-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20190914_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='byte_distribution',
        ),
        migrations.RemoveField(
            model_name='fileinfo',
            name='file_magic',
        ),
        migrations.RemoveField(
            model_name='fileinfo',
            name='printablestr_txt',
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='exec_ability',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='network_ability',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='rw_ability',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='accessed_time',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='create_time',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='link_date',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='modified_time',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='pe_timeDateStamp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='signing_date',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
