# Generated by Django 2.1 on 2019-12-05 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file_upload')),
                ('uploaded_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(blank=True)),
                ('file_hash_sha1', models.CharField(max_length=40)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('peutils_packed', models.CharField(blank=True, default=[], max_length=200)),
                ('entropy', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('create_time', models.CharField(blank=True, max_length=30)),
                ('modified_time', models.CharField(blank=True, max_length=30)),
                ('accessed_time', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=60)),
                ('product', models.CharField(blank=True, max_length=50)),
                ('prod_version', models.CharField(blank=True, max_length=40)),
                ('file_version', models.CharField(blank=True, max_length=40)),
                ('machine_type', models.CharField(blank=True, max_length=20)),
                ('signature_verification', models.CharField(max_length=100)),
                ('link_date', models.CharField(blank=True, max_length=30)),
                ('signing_date', models.CharField(blank=True, max_length=30)),
                ('signer', models.TextField(blank=True, default=[])),
                ('counter_signer', models.TextField(blank=True, default=[])),
                ('pe_machine', models.IntegerField(blank=True, null=True)),
                ('pe_sectionNum', models.IntegerField(blank=True, null=True)),
                ('pe_timeDateStamp', models.IntegerField(blank=True, null=True)),
                ('pe_characteristics', models.IntegerField(blank=True, null=True)),
                ('pe_entryPoint', models.IntegerField(blank=True, null=True)),
                ('pe_sections', models.TextField(blank=True, default=[])),
                ('pe_imports', models.TextField(blank=True, default={})),
                ('pe_exports', models.TextField(blank=True, default=[])),
                ('printablestr_txt', models.IntegerField(blank=True, null=True)),
                ('byte_distribution', models.TextField(blank=True)),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('upload_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploadFile.File')),
            ],
        ),
    ]
