# Generated by Django 2.1 on 2019-11-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0007_remove_fileinfo_file_magic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='pe_sections',
            field=models.TextField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='peutils_packed',
            field=models.CharField(blank=True, default=[], max_length=200),
        ),
    ]
