# Generated by Django 2.1 on 2019-11-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0008_auto_20191111_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
